version: '2'
services:
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
        links:
            - cache
    cache:
        build:
            context: ./
            dockerfile: ./cache.docker
        ports:
            - "11211:11211"