version: '2'
sevices:
  localcli:
    build: ./
    image: "buonzz/php-production-cli"
    volumes:
      - .:/code
    links:
      - localcache:localcache
  localcache:
    image: memcached
    ports:
      - "11211:11211"