version: '2'
services:
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
        links:
            - cache
    cache:
        image: "memcached:latest"