version: '2'
services:
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        ports:
            - 9200:9200